//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.ktelabs.testovoe.soap.dto;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="startSchedule" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="endSchedule" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="startDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="endDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="amountMinutesOnSession" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startSchedule",
    "endSchedule",
    "startDay",
    "endDay",
    "amountMinutesOnSession"
})
@XmlRootElement(name = "getScheduleRequest")
public class GetScheduleRequest {

    @XmlElement(required = true)
    protected String startSchedule;
    @XmlElement(required = true)
    protected String endSchedule;
    @XmlElement(required = true)
    protected String startDay;
    @XmlElement(required = true)
    protected String endDay;
    @XmlElement(required = true)
    protected String amountMinutesOnSession;

    /**
     * Gets the value of the startSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartSchedule() {
        return startSchedule;
    }

    /**
     * Sets the value of the startSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartSchedule(String value) {
        this.startSchedule = value;
    }

    /**
     * Gets the value of the endSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndSchedule() {
        return endSchedule;
    }

    /**
     * Sets the value of the endSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndSchedule(String value) {
        this.endSchedule = value;
    }

    /**
     * Gets the value of the startDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDay() {
        return startDay;
    }

    /**
     * Sets the value of the startDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDay(String value) {
        this.startDay = value;
    }

    /**
     * Gets the value of the endDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDay() {
        return endDay;
    }

    /**
     * Sets the value of the endDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDay(String value) {
        this.endDay = value;
    }

    /**
     * Gets the value of the amountMinutesOnSession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmountMinutesOnSession() {
        return amountMinutesOnSession;
    }

    /**
     * Sets the value of the amountMinutesOnSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmountMinutesOnSession(String value) {
        this.amountMinutesOnSession = value;
    }

}
